root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.base.json
ignorePatterns:
  - '**/*'
plugins:
  - '@typescript-eslint'
  - '@nrwl/nx'
  - jest
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-parameter-properties': off
  '@nrwl/nx/enforce-module-boundaries':
    - error
    - enforceBuildableLibDependency: true
      allow: []
      depConstraints:
        - sourceTag: '*'
          onlyDependOnLibsWithTags:
            - '*'
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - plugin:@nrwl/nx/typescript
    rules:
      '@typescript-eslint/no-unused-vars': off
  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - plugin:@nrwl/nx/javascript
    rules: {}
  - files:
      - '*.spec.ts*'
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
      - plugin:jest-formatting/recommended
    env:
      jest/globals: true
    rules:
      '@typescript-eslint/no-explicit-any': off
