extends:
  - plugin:@nrwl/nx/react-typescript
  - ../../.eslintrc.yml
  - next
  - next/core-web-vitals
ignorePatterns:
  - '!**/*'
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
      - '*.js'
      - '*.jsx'
    rules:
      '@next/next/no-html-link-for-pages':
        - error
        - apps/fe-wtc-tech-test/pages
  - files:
      - '*.ts'
      - '*.tsx'
    rules: {}
  - files:
      - '*.js'
      - '*.jsx'
    rules: {}
env:
  jest: true
