extends:
  - plugin:cypress/recommended
  - ../../.eslintrc.yml
ignorePatterns:
  - '!**/*'
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
      - '*.js'
      - '*.jsx'
    rules:
      jest/expect-expect: off
